// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteCasamento.Data;

#nullable disable

namespace SiteCasamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428194152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("SiteCasamento.Models.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataUltimaResposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneUltimos4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Convites");
                });

            modelBuilder.Entity("SiteCasamento.Models.PagamentoPix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Loja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeConvidado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("PresenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresenteId");

                    b.ToTable("PagamentosPix");
                });

            modelBuilder.Entity("SiteCasamento.Models.PessoaConvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConviteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Vai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConviteId");

                    b.ToTable("PessoasConvite");
                });

            modelBuilder.Entity("SiteCasamento.Models.Presente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataReserva")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacaoEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReservadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Presentes");
                });

            modelBuilder.Entity("SiteCasamento.Models.PagamentoPix", b =>
                {
                    b.HasOne("SiteCasamento.Models.Presente", "Presente")
                        .WithMany()
                        .HasForeignKey("PresenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presente");
                });

            modelBuilder.Entity("SiteCasamento.Models.PessoaConvite", b =>
                {
                    b.HasOne("SiteCasamento.Models.Convite", "Convite")
                        .WithMany("Pessoas")
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convite");
                });

            modelBuilder.Entity("SiteCasamento.Models.Convite", b =>
                {
                    b.Navigation("Pessoas");
                });
#pragma warning restore 612, 618
        }
    }
}
